services:
  postgres:
    image: postgres:16
    container_name: tms_postgres
    environment:
      POSTGRES_DB: tms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - tms_pgdata:/var/lib/postgresql/data

volumes:
  tms_pgdata: